services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_model_data_volume:/root/.ollama/models
    environment:
      - OLLAMA_HOST=${OLLAMA_URL}
      - OLLAMA_MODEL_NAME=${OLLAMA_MODEL_NAME}
    entrypoint: ["/bin/sh", "-c", "ollama serve"]
    # docker exec ollama ollama pull ${OLLAMA_MODEL_NAME}
    # docker exec ollama ollama pull deepseek-r1:1.5b
    networks:
      - app-network

  app:
    image: python:3.12.7-slim
    container_name: app
    restart: no
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - site-packages_data_volume:/usr/local/lib/python3.12/site-packages
    working_dir: /app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && python backend/app.py"
    # pip install --no-cache-dir -r requirements.txt && python backend/app.py
    networks:
      - app-network
  db:
    image: mysql:8.0.31
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: db
    ports:
      - "3306:3306"
    volumes:
      - hbm_mysql_data_volume:/var/lib/mysql
      - ./db/hbm_db_init.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app-network

  redis:
    image: redis:7.0
    container_name: redis
    restart: no
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    image: nginx:1.25.3
    container_name: nginx
    restart: no
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  hbm_mysql_data_volume:
  site-packages_data_volume:
  ollama_model_data_volume: